version: '3.6'

services:
  web:
    build:
      context: ./docker/nginx
      target: base
    volumes:
      - type: bind
        source: ./app
        target: /user/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=angulardocker.com
      - NGINX_PORT=80